[build]
  base = "/"
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[functions]
  directory = "functions/"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
from = "/*"
to = "/page-not-found"
status = 404